In [1]:
"Hello World"

'Hello World'

In [2]:
greeting = "Hello World" # this is a string variable (<- this is a comment)

In [3]:
greeting

'Hello World'

In [4]:
greeting = "Hello World"
greeting

'Hello World'

In [5]:
print(greeting)

Hello World


In [6]:
a = 2
b = 15

In [7]:
a + b

17

In [8]:
my_sum = a + b # get sum of a & b

In [9]:
# print sum
my_sum

17

In [10]:
my_product = a * b
my_product

30

In [11]:
import numpy as np

In [12]:
ages_list = [25, 30, 35, 40, 45] # this is a Python list

In [13]:
ages = np.array(ages_list) # this is a numpy array

In [14]:
ages

array([25, 30, 35, 40, 45])

In [15]:
# you can also do this in a single line
ages = np.array([25, 30, 35, 40, 45, 50, 55])
ages

array([25, 30, 35, 40, 45, 50, 55])

In [16]:
ages[0]

25

In [17]:
ages[6]

55

In [18]:
ages[-1] # this is the last element

55

In [19]:
ages[0:4] # goes from index = 0 to 3 (first 4 elements)

array([25, 30, 35, 40])

In [20]:
ages[:4] # goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [21]:
ages[1:4] # goes from index = 1 to 3 (2nd to 4th elements)

array([30, 35, 40])

In [22]:
ages[1:] #goes from index = 1 to last element (same result as above)

array([30, 35, 40, 45, 50, 55])

In [23]:
ages[:] # goes from first to last element (same as ages)

array([25, 30, 35, 40, 45, 50, 55])

In [24]:
ages[::2] # keeps every 2nd element only

array([25, 35, 45, 55])

In [25]:
ages[::-1] # reverses order of elements

array([55, 50, 45, 40, 35, 30, 25])

In [26]:
ages[ages<40]

array([25, 30, 35])

In [27]:
ages[ages<=40]

array([25, 30, 35, 40])

In [28]:
len(ages)

7

In [29]:
ages_mean = np.mean(ages)
ages_mean

40.0

In [30]:
np.min(ages)

25

In [31]:
np.max(ages)

55